car_show_car:
    path:     /car/show/{carId}
    defaults: { _controller: CarBundle:Default:showCar }
car_add_fuelling:
    path:     /car/fueling/{carId}
    defaults: { _controller: CarBundle:Default:addFueling }
car_add_cost:
    path:     /car/addcost/{carId}
    defaults: { _controller: CarBundle:Default:addCost }
car_list_of_cars:
    path:     /car/list
    defaults: { _controller: CarBundle:Default:listAllCars }
car_add_car:
    path:     /car/add
    defaults: { _controller: CarBundle:Default:addCar }