car_home:
    path:     /{_locale}/car/home
    defaults: { _controller: CarBundle:Default:home }
car_home2:
    path:     /{_locale}/car/
    defaults: { _controller: CarBundle:Default:home }
car_show_car:
    path:     /{_locale}/car/show/{carId}
    defaults: { _controller: CarBundle:Default:showCar }
    requirements:
        _locale: '%app.locales%'
car_add_fuelling:
    path:     /{_locale}/car/fueling/{carId}/{masterFuelingId}
    defaults: { _controller: CarBundle:Default:addFueling, masterFuelingId:0 }
car_edit_fueling:
    path:     /{_locale}/car/edit/fueling/{fuelingId}
    defaults: { _controller: CarBundle:Edit:editFueling }
car_add_cost:
    path:     /{_locale}/car/addcost/{carId}
    defaults: { _controller: CarBundle:Default:addCost }

car_add_image:
    path:     /{_locale}/car/addimage/{carId}
    defaults: { _controller: CarBundle:Default:addImage }
car_edit_cost:
    path:     /{_locale}/car/edit/cost/{costId}
    defaults: { _controller: CarBundle:Edit:editCost }
car_list_of_cars:
    path:     /{_locale}/car/list
    defaults: { _controller: CarBundle:Default:listUserCars }
    requirements: 
        _locale: '%app.locales%'
car_add_car:
    path:     /{_locale}/car/add
    defaults: { _controller: CarBundle:Default:addCar }
car_edit_car:
    path:     /{_locale}/car/edit/car/{carId}
    defaults: { _controller: CarBundle:Edit:editCar }
car_get_stat_image:
    path:     /{_locale}/car/getstatimage/{carId}
    defaults: { _controller: CarBundle:Default:getStatImage }
car_export_data:
    path:     /{_locale}/car/export/{carId}
    defaults: { _controller: CarBundle:Data:export }
car_get_charts:
    path:     /{_locale}/car/charts/{carId}
    defaults: { _controller: CarBundle:Statistics:drawCharts }    defaults: { _controller: CarBundle:Data:export }
car_login:
    path:     /{_locale}/car/login
    defaults: { _controller: CarBundle:User:login }
