car_homepage:
    path:     /car/show/{carId}
    defaults: { _controller: CarBundle:Default:index }
car_add_fuelling:
    path:     /car/fueling/{carId}
    defaults: { _controller: CarBundle:Default:addFueling }
