car_home:
    path:     /car/home
    defaults: { _controller: CarBundle:Default:home }
car_show_car:
    path:     /{_locale}/car/show/{carId}
    defaults: { _controller: CarBundle:Default:showCar }
    requirements:
        _locale: '%app.locales%'
car_add_fuelling:
    path:     /car/fueling/{carId}
    defaults: { _controller: CarBundle:Default:addFueling }
car_edit_fueling:
    path:     /car/edit/fueling/{fuelingId}
    defaults: { _controller: CarBundle:Edit:editFueling }
car_add_cost:
    path:     /car/addcost/{carId}
    defaults: { _controller: CarBundle:Default:addCost }
car_edit_cost:
    path:     /car/edit/cost/{costId}
    defaults: { _controller: CarBundle:Edit:editCost }
car_list_of_cars:
    path:     /{_locale}/car/list
    defaults: { _controller: CarBundle:Default:listAllCars }
    requirements: 
        _locale: '%app.locales%'
car_list_of_cars2:
    path:     /{_locale}/car/
    defaults: { _controller: CarBundle:Default:listAllCars }
    requirements: 
        _locale: '%app.locales%'
car_add_car:
    path:     /car/add
    defaults: { _controller: CarBundle:Default:addCar }
car_edit_car:
    path:     /{_locale}/car/edit/car/{carId}
    defaults: { _controller: CarBundle:Edit:editCar }
car_get_stat_image:
    path:     /{_locale}/car/getstatimage/{carId}
    defaults: { _controller: CarBundle:Default:getStatImage }