car_homepage:
    path:     /car/show/{carId}
    defaults: { _controller: CarBundle:Default:index }
car_add_fuelling:
    path:     /car/fueling/{carId}
    defaults: { _controller: CarBundle:Default:addFueling }
car_list_of_cars:
    path:     /car/list
    defaults: { _controller: CarBundle:Default:listAllCars }